ignore_merge_commits = true
tag_prefix = "v"
branch_whitelist = ["main"]
pre_bump_hooks = [
  "uv version {{version}} --no-sync",
  "mise run check",
]
post_bump_hooks = [
  "git push --atomic origin HEAD {{version_tag}}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "lauritsk"
repository = "sambatui"

[[changelog.authors]]
signature = "karl@laurits.dev"
username = "lauritsk"
